# Site settings
title: Open Science MOOC
description: ""

url: "http://opensciencemooc.eu"
baseurl: ""

header-img: img/home-bg.jpg
headercolor: "#000000"
logo: /img/logos/mooc_logo.png

github_username: OpenScienceMOOC
twitter_username: OpenScienceMOOC
altmetric: true

permalink: pretty
paginate: 10
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md"
]

collections:
  modules:
    output: true
  people:
    output: true

defaults:
  # default to people's layout for people's page
  -
    scope:
      path: ""
      type: "people"
    values:
      layout: "profile"
  # Set a avatar variable to be able to loop trought people's avatar in
  # people's page.
  -
    scope:
      path: "assets/img/people"
    values:
      avatar: true
