# Site settings
title: Open Science MOOC
description: ""

url: "https://OpenScienceMOOC.github.io"
baseurl: "/site"

header-img: img/home-bg.jpg
headercolor: "#000000"
logo: /img/logos/mooc_logo.png

github_username: OpenScienceMOOC
twitter_username: OpenSci_MOOC
altmetric: true

permalink: pretty
paginate: 10
exclude: [
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md"
]

collections:
  modules:
    output: true
  people:
    output: true

