# ------------------------------
# Configuration file
# ------------------------------

# Website specific
baseURL: https://opensciencemooc.eu/
languageCode: en-us
title: Open Science MOOC

params:
  description: "Insert your website description here"
  twitter: "@OpenScienceMOOC" 

# Hugo specific
disableHugoGeneratorInject: true
disableKinds: [
  "404",
  "page",
  "RSS", 
  "robotsTXT", 
  "section",
  "single",
  "sitemap", 
  "taxonomy", 
  "taxonomyTerm", 
]
metaDataFormat: "yaml"
